#!/usr/bin/env python3
"""
Rosalind Problem: GC (Computing GC Content)
Problem ID: GC
URL: http://rosalind.info/problems/gc/

Given: At most 10 DNA strings in FASTA format.
Return: ID of string with highest GC-content, followed by GC-content.
"""

def parse_fasta(fasta_string: str) -> dict:
    """
    Parses a FASTA string into a dictionary of {sequence_id: dna_sequence}.

    Args:
        fasta_string (str): Raw FASTA format data.

    Returns:
        dict: Dictionary mapping sequence IDs to their DNA sequences.
    """
    sequences = {}
    current_id = None
    current_seq = []

    for line in fasta_string.strip().split('\n'):
        if line.startswith('>'):
            # Save previous sequence if exists
            if current_id is not None:
                sequences[current_id] = ''.join(current_seq)

            # Start new sequence
            current_id = line[1:].strip()  # Remove '>' and trim
            current_seq = []
        else:
            # Append sequence line
            current_seq.append(line.strip())

    # Don't forget the last sequence
    if current_id is not None:
        sequences[current_id] = ''.join(current_seq)

    return sequences

def calculate_gc_content(dna_string: str) -> float:
    """
    Calculates GC-content percentage for a DNA string.

    Args:
        dna_string (str): DNA sequence.

    Returns:
        float: GC-content percentage.
    """
    if not dna_string:
        return 0.0

    gc_count = dna_string.count('G') + dna_string.count('C')
    total_length = len(dna_string)

    return (gc_count / total_length) * 100

def main():
    # Read the input FASTA data (paste your dataset here)
    # IMPORTANT: Keep the exact formatting with > symbols and newlines
    fasta_data = """>Rosalind_9252
AGAGCTCGGGTTGGCAGGCAGAAATAGTAAACTTGTGAGTCGACCCGATGACGCCCTCAT
CCGAGTCATAGCGTGCGTAGCTACGCTCACATTCTATATGGTATTGGGAAGGAAAGACAC
GAGGTCTCAAGCACTTGTTTGAAGCCTAGATATATCTTGCTTTCGGGTGGTCGGTTGTGG
CTTTACTAGTGACAGTCCCGAAAGGTTTTCTGCCCAAGGGTCTCGCATAACCCTAAACAC
GATTCTCCCTCTTGCGGGGCAGCCTTGGCGCGCAGAGGTCAGAAGGTATCCATAGCCACT
ATAAGGGTCATCGATGTTATTAGCAATATACTGCGCCGCTCCAGCTAGCAGTCGGGCGTT
ATGGAAAAGGGAGTTACTATTCCAATAGCCGTGTAATCGCTAAGACTGCTCACTTCGGAC
ACAGCGCAAGTGGCACCCGGACTTTTTCGGCAACTAGTGCTGAGCCATCACGCTGAACCG
CACCCGGGTTCATAATCGTCAAAATAGACCCGCTACAACTGGTTTTTTTTCCAAACGGTA
CCTGGGATCGTAGTGGCAAAGACCCTCGAGACTTTGTCAGTTTCAGAGACTAAGCTAATG
ATGTCGACCAGACATTTTGCATCTCTCAGTGGACGGTGTCTAGCCATCGACGGATAAAGC
CAATTTCGCGAAATGCATGCGCTACAAGAGGGCGATGACTTTAGTGTCCTGGTCTAATAG
GAGTACGTCGATAAGTATAACCTGTTGAACAAAACCAGCTGAATAAATGAACCTCGTCTC
ATCTTTCCTCCGGCCCTCTTGTACGCATCAAGGCCCTGGACTGAACCTATCTGCGCGATC
GGAGGAGGTGACTCAGATTCCATATGCCTTATCAAAGGTAAACAGCGTTCGCCGCAGTAC
GAGCATAGGCTATTGTGGACTTACCTAGCTCGTCGACGTAACATCGTTAATAACTGACCA
GCGCCGAG
>Rosalind_6049
GACAGCAATACCTACCGTTTTGTGTAAACCATTACAGAATAGGGAGAGGAAAGGGCAACC
ATGCCGTGTAGACTCGGAAAATGAGCGCCAGGAGAGGCCAACCATGTGGATTCAAGATGG
GGGGATCAGCCTATACAACTGCCTTCCGCTAAGACGGGCGCAACACACTTAAAGTTTGTT
TCAGGGCGGTCATATGCAGCTCGAGATCTAATGCTGATGGGGCAGGTATCAGTCGGGAAA
ACGAGCCGCTTTTAGGGCGACGAAATAAAGAGCTCGCGCCCGGATGACCCTGTCGGGACA
GGTCGAAAACAATAGTCTACAGGCTCTAGTCACAACGGTCAATCATGGTTAGAGATAATC
TTAAGAGTACGCGCTTATTAATTGGTAATTTAAGCCTTCGCGCTTAACTAGCTGAAAGCT
CCTAGACTCCCCTCCGTTAAACGCTTGGCTAGTCCCGTATACCTCACGGCAGAGTAAAAC
ATGGATATTTACTTGTGTAAAGCTACTTTTGTCTGAGCCAAGTAAACACGCTCGTCAAGG
GTGGGAGCAGATTGAGAATTACGTCTAGGCCTTTAGTTCTGTACATGATAACTGTCGTGT
CGGTCGATGTGTGATCCAACGTACATTACAGCAAAGCTGCATAGTGACGGCTATAATGAG
TGCATCTATAAGAAGCCAATCTCTTCTCAAATACAGAGCGGATACCTGAGATTCATCGGA
GGAGACACATGAACCTCCTCGCGGCGTAAAGACCCTGCGATCTATACTATCGTTCCCGAG
CAACGAAGTTATTCTCCGGGCTGATACTAACCTAGCACAAGTGGGGATTATCCTC
>Rosalind_9878
CAATCTTTGTTGTAGGTGAGATTGGCACGTATGAACCCCCTGAGACAAACCGAATATTCT
ACTAAAATATGGGAGTCAGTCCGGCTGCCTTACAACAGACACACGTGACAGTGCTATAGT
ACGTTTCATGACGTACCGGTAGTGTTACCAAGTACGGTGAACCCTTCCGATCACCGCGGT
TGAGTAACTTGCCTCCCTTCACCGCTGCAGCCGAGGCACAGCAGAAACATACGTACTACA
GTGGCGCTGCCAGGGTCGGGCAGATAAGCCCGATCTTCTCGCCTCAAAGACGCTGCGGGT
CCTATGGGGACTGAGGATTTTTCATTCACCGCCACTGTCCTTATCTCACCTTGTTTCAAG
ATAGCGATTTAGGTGCAGTTCAAGTTTTCCCCGTGTCAACCCGGGTAGGCATGTCCACGC
AGCTGCACTCCGTAGGGGACGCCGCGATGGGAGATAAATGGTTGTCTACGATAAGGAATC
GCGGCGGTGTTTTGGAGAGACGACAGTGAGGATGGGCCACATACCTCTTTAGGTACTCTG
TACTTCGAAGATTGAAGAATTTGACCGGGATGGTGCTTCATTGAAGGTAAGAGAACTGGT
CACAAAATTGGAACGTGAACACCACATAAGCTAGCCGAAGCCACTCTGTTCCTTCCGGGA
TCCCATAAAGCTCCCTTTCCTAGGTCTCGAAAGTCGGTATTGGCGGACCATGGGGCCCTG
ACGACCACACAATGGGTGAGCATAGCGAAGTGAGATATTAGATACGTGTAGACTAGTGAC
TTTAGGTAGATGTACACGACTCAACTGTCTGTATACCACACGTGACTGGTCGTGATAGAC
AGCGCAGGAATAGTACCGATCTTAACCCATCAGCAATGATG
>Rosalind_3031
AGGTGTTACCACCTCTATCGTAAAACTGCTCAGTGAAGTATTTAATGCATCTGCTCTAAT
ATTTTAAGCGGATTGATGTTATGTTAGTGAAGGCACAGACACACTTCTTTCGGCAGTTCG
CGTTGTGTCAAGTCCCCTCCCTTGTTTTGGCTCGATCAGAGGCTGTGACACGCTCTCCAG
GCACAATGACATCCGCACCCTAACATGTTCGGGCAACGTTCAGTGATTATTGTGTGGTCG
AATCCGTCGTAGACGCGAAATAGATCCCCGATAGGAAGCACCCCAACGGATAGGTGATAC
ACAAGCCCTAATGAGCCAACTTCCTCCAACCCGAAAAGGCTCTTGAGTCGCCTTTGAGCG
CTTATAACACTTCTGCGCGGCCTTAATTGCAGAAGGAATCGCCCCAATACGATAGCCTAA
TCGAAAATTATACCTCCAGGGCACAGATAGCCTGTAAATGCCTCTATTCGACTATGTAGA
ACGGCGTTTATATGAGAAGTTTCACCACTTGTTCTGAGCTGTTTACGCCGGTTTCCTCCG
CACATTGAGGCCGAGTCAACAGTATGGAAGCCCGTACCTCCGGCGCTCGTGGTTGCATGG
TGGTACGATTGCCCCAGTCTGGGGTTCCTGGTGACTACCTATCAAATGCGTCGCTAGGGC
GGCTCATCTGTAAAATGGTATGTTTTGTAAGGCGTTGGTCACGGAGTAATTATGGACGAT
GAATCCGCGCCGGCTCCTGTCTAGGGAGCCTCCTAGCTAACCAACGTTCTTCTGGTCCCC
TTCTGGCGCCACGAGGTAGCTTGGACAAAAACCTAGCGCAGTTAAGGGCGAGCTGTAGCT
CATCAGCACGGGAGTATCATATGCGACAACATCTGGATATACGACACGTGTCTAA
>Rosalind_6026
GGTGCTCCGTATGGTCGTGCCCCTTGCGGCCGCAACCATTCTTTCACCCTTGCAGTCTGG
AACAATCACAAAACTGAACCAAAAACGCAGTCTGGCCCGAGCAGTTTCTGCAGAGCCAAA
CAATTTCCGGATGAGTCGAAGGTACTCAGTCAAAGCCCGTGACTCGCAGCTCGTTAAGAG
AGGCCTACAATTGGTAGGCCTTGTCACATCCTTCATAGGACTATGAGTTAATGCTAAAGA
GGCTGTTCTCCGCCACCGTGAATGTCAGATAGACAATAGGTTTCCCGCTACTCCTACTCC
ATCTAAGGACCCTCCACGATGAATCGCGAGGCACAGCCAGCTTGAGTGAGTGGAGGTAAT
TTCATGGCATAGTATCTCGCTCGACCGTTGCCCGCGCGATTAATCTCCCTTTAATATGCG
GTGTAAGTGATCTTCCCCCTGCAACGTTGCCCATCCTTATTAATGTAAGCGGGATCAGTC
CGCTCATTGCGGTAGGTTCGAAGAGCGGCTTGACTAACGGAGTCAACTTGGTGTGAAGCA
GTTGCACGTGAGCGGGTTCACTTATCGTCTCTTCCGCTTCTGAGACTTGACGCCTTGGCC
GATGGCAACCAGTCAACTGCTTTCCGAAGCGGCGCAAGGTTCCGCCTTAAGGTAAGCATG
GAATAGGGGCCTCGCGGGCAACCCGCCGTTCCTCGTGCCGCGATATTGCAGTTCAGGTCG
CGTTAACGGGCAGAAGACCCACTAAGCACGTATAGTGTATAACTCTGATGCTTTATCTGG
TCGAACTTAGTCAGACCACGCGGTAATAGGCATGGCTTGTTCTGACGCTACCTAGCAACG
GACAATCATGTCACGTGCCCAACCCT"""

    # 1. Parse FASTA
    sequences = parse_fasta(fasta_data)

    # 2. Calculate GC-content for each
    gc_results = {}
    for seq_id, dna_seq in sequences.items():
        gc_results[seq_id] = calculate_gc_content(dna_seq)

    # 3. Find the sequence with maximum GC-content
    max_id = max(gc_results, key=gc_results.get)
    max_gc = gc_results[max_id]

    # 4. Print result in required format
    print(max_id)
    print(f"{max_gc:.6f}")  # Format to 6 decimal places

    # Optional: Save output
    # with open('gc_output.txt', 'w') as f:
    #     f.write(f"{max_id}\n{max_gc:.6f}")

if __name__ == "__main__":
    main()