#!/usr/bin/env python3
"""
Rosalind Problem: HAMM (Counting Point Mutations)
Problem ID: HAMM
URL: http://rosalind.info/problems/hamm/

Given: Two DNA strings s and t of equal length (≤ 1000 bp).
Return: The Hamming distance dH(s,t) - number of differing positions.
"""

def hamming_distance(seq1: str, seq2: str) -> int:
    """
    Calculates Hamming distance between two equal-length sequences.

    Args:
        seq1 (str): First DNA sequence.
        seq2 (str): Second DNA sequence.

    Returns:
        int: Number of positions where the two sequences differ.

    Raises:
        ValueError: If sequences have different lengths.
    """
    if len(seq1) != len(seq2):
        raise ValueError("Sequences must have equal length")

    # Count positions where characters differ
    distance = 0
    for base1, base2 in zip(seq1, seq2):
        if base1 != base2:
            distance += 1

    return distance

def main():
    # Read input (paste your dataset here)
    # Format: two DNA strings on separate lines
    data = """AATGTTTGCGTGGGACGAGTGCCGTCCTACACCGCATCCTTACAGTGGCTCAATCCTGGACGTACTCTTGGCTGGCATCCCGTGACACTTATTGTTCTTAGACCAATAATTACGAAGAGCGCCCCAATGAATATCAGAGAAGACCATGCGAGTCTTCATCCATGGTACGTCCATATTAATTTTCATCAGCTAAAAATAATCCCGCGGCCGCACACCGTCCACAGTTAGCGACTGGCACTTCCGAATGTAGCTGATCATGTTATGTACATCCCCCCGCGCGCACAGCCCCGCCGATCGTAGCTCTCGAACAAACCAGTGTTCACTACTTTTAACTTCTGAAATCGTCCCCCGAGTAATTTTACAGCACGTAGGCCGACGGGTTAATGTGTAATCTCCACTAGCAGCCGCGAAGAATTTGTCCTCGAGTGAACAGGCATTCTACAGCCTTGTGCAAGGCGGACCCTGGCCATAAGGCACCGGGCACGCATTGAAAGAGAGGACAGCGCTCTTCTACTAGCTTCGCTCTCAAGTGAGTGAGACTGGTTCGCGAAGTAGCATGGTACCCTGCTATAAGACCAAGATAGTAAGGTTCCTGACGCATCTATGCTAGGTCAGGGTGGCGTGCGTTTCGACTTGCGTGGTTACCTACGTGTATCTTCTTAATAGCAAGCCGTGGAGTACTGTTTGTGTATGCACCTAGTATAGACGGTTGGAGCATCACTATCGGCCGGGTACCGAGAAAAAAAGTAAATACTCGACCTGGAGTATCGGACAGGTCCCTTGTTTAGCTATAATATTACAGGCGCCATGGATAGATCTTCTCTAGGAAATAGTTTCTTAGGGGCGGCTTATCTCCGAAAGGTTGAACCGCTCATATCTTGGATTGGTTTATAAAGGACTCTTAGAACGACTAATTACACGTGTACATTTG
AAGGTGGGGCTGGTAAAACTGTAGGGGTAGACCGCAAGGTTCTAGGCATCTAATCCGTCACGTTTGCGTGCATGACATACAGTGACATCGATGGTTATGAGACGGTTAAGCCAGGCTGCCCGGCAAAAAAAAAGCGGGGGTAGACCTGTGTATCTTAATGCATGGTCTTGTTATATTATCCGCGTTATAATGTTTAGAGAACCGCCCGTTAGAATGCCACACAATGATGAAGGCGCCCGCGCTTTTGGACAGCTGCCGGTTATATGCCACACCCTGTGAGTTTAGCCAGACTGTTAGAAGGCCTGTTACTAACATAGTTTCTATCATGGAAACTACGGGTCGCGTCCAGAGCGCGACGGAGAGGCCTGTAGGCCTCAGTATATCTGCGTTATAGCCAAATCAAGACGCGACCTATTATCTTGAAGTCGACCAACCATTGCCCATAACCGTTTTAGTCCGACCCTGACAAGTAGGTATAGACCCCTCCCATGGGAACAGCCCACAATACCTCTACGCGGTGCCGGCACCCCGACGTCAGACTACCGGTCGAATTGGCACGGTAGTCGGCGCGATTGGTGACATAGTAAATTCCCGGAGCCTGCAAGGTTAAGTCAGTGCAGCGAGAATTTAGTCTTCCAAGTGTGCCTTTAATCAATCGTCCAGGAGCGAGCCTTAAGATATCTTTACATAGGGCAGGCACTATATAATTATGGAACTACTCCGTAGACACGAAACATCGGATACTAGTAAATCCCTCCACCGGGGTTGATAACACTGACTGCGATTTGCTATACCATTTCGACGGTTACGTATACTTAAACTCTAGGTTACCCCTTAAAACCGGCCGCTTATCTCAGCGGAAGTACTATCTAGATCTCGTTGAGGCCGTTATTAAGAACGATTCTAACGCCAAAGTATTCGGCTGGCGTAA"""

    # Split into two sequences
    lines = data.strip().split('\n')
    if len(lines) != 2:
        print("Error: Input must contain exactly two lines")
        return

    s = lines[0].strip()
    t = lines[1].strip()

    # Calculate Hamming distance
    try:
        result = hamming_distance(s, t)
        print(result)
    except ValueError as e:
        print(f"Error: {e}")

    # Optional: Save output
    # with open('hamm_output.txt', 'w') as f:
    #     f.write(str(result))

if __name__ == "__main__":
    main()