import re

motif_pattern = re.compile(r'(?=(N[^P][ST][^P]))')

sequences = {
    "Q0IBF4": """MDGIDRNPRQKLSLLLVAGRHHLSSRDLRELVEFLQNEDCGFDVSLQISDPTQQPELLEL
HRLVVTPSLVKLQPQPKQVFAGSSIFQQLRGWLPRWQQDEVVSGLGLSLKPTELDGSRTQ
RELQLEDQLLVLRQENETLIDRLQAQERLLRMVAHELRTPLTAATLAVQSQELGQIDIHR
FRDVLKRRLEEIALLSKDLLEVGSTRWEALFNPQRLDLTSVAAEAILELEKLWLGRDVTI
HTDIPADLPKVFADQRRMRQVLLNLLENALKYTPNGGLISLTMLHRTSQWVQVSISDSGP
GIPEEEQQRIFLDRVRLPQTSAGASGFGVGLSVCRRIVEVHGGRIWVISEPEKGACFTFN
VPIWQGQGQEKENVVLTEGQAEP""",
    
    "A5A3H2": """MNTATGVIALLVLATVIGCIEAEDTRADLQGGEAAEKVFRRSPTCIPSGQPCPYNENYCS
QSCTFKENENANTVKRCD"""
}

for uid, seq in sequences.items():
    # remove newlines
    seq = seq.replace("\n", "")
    positions = [m.start() + 1 for m in motif_pattern.finditer(seq)]
    if positions:
        print(uid)
        print(" ".join(map(str, positions)))
