# ============================================
# ROSALIND PROBLEM: RNA - Transcribing DNA into RNA
# INPUT: Paste Rosalind's DNA string 't' below
# OUTPUT: The RNA string 'u' (all T replaced by U)
# ============================================

t = "GAGATCCGAGACAGTTGCGCATCCGCTTACTCTATCCCACCATTAGTCGTCTGCTTATCCTGTCGAACAGCGATTAATGTTATTCGCCAGAAGAATACGATCGGGGTAAATTGTCATTCTATAAGTGATAACGCGGGTCACTTCAGTTCGTGCCCACCAACATTTGCCGGGTGCAATCCTCCGAAGTCCGCAAGTGGCAGGACTTCGGTCGGGGCTCGTAATATCAACCCCAGGACCGAGTGGCTGCTCGTTCTATGCCGGGAAAGGTAACACGAGCGCTAAAAACGCAAGGTTACGGCGCACCGTTGCATCTACGGTGGTCCGATCGCCGGACTATTGACCCTGGGCGGAAAGAAGGGCTGGCTGGAAATTCTATCACGAAAACAAAGTTCGCCCGTCAATATCTATCAACTAGGGACCCTCGCGCTGGTAAATTCGCTAACGCAATAGCTGCAACGAGTAGGCTCAGTCCACTGGGTCGATAATGCTAACACACATGGCTCGTGGTGTGAATACCCTGCTGCTGCCGGTGATTATACGCCGACAAGGTAAAACCGCATAAGACAGGTCCCCGCGGAAATTTTCTTGCGCACATTGTCATTTACCGCGAGATGCCGGAATGAGTGCTTCGCCACGCGCGATACCGGGAATCATACAATAATTCGGATTGAGTCCGGGTCCTGGCACTACTCCAACGAGGAGGATGATGCAGCGAACGGCACGGGGCACGCGGCAGGATGTGCTACTTAGACTCAAAAAAATCCCGCCATTGGAGTAGCAGAGTTCTTAATTGTGTATAATCGCACCCAAGAAGCAATTAGTCTGATGAGAGCGAAATCGCGCTGGGGTCTATGGTCTCCTGTGGAGCTTCCATCAGTGGGTCAGCACTTTCCAAACATTTGCCCGGCAGTTGTCCACCAAAGATCCCTAGGTGGGTTATCATTCTAACATCCGCGGGAACCACATGCTCAGGACCTACATGT"

# -------------------------------------------------
# DO NOT EDIT BELOW THIS LINE
# -------------------------------------------------
# The core operation: replace all 'T' with 'U'
u = t.replace('T', 'U')

print("Your Rosalind answer is the string below:")
print(u)