# =========================================================
# ROSALIND PROBLEM: SUBS - Finding a Substring in a String
# INPUT: Paste Rosalind's DNA string 's' and substring 't'
# OUTPUT: All starting positions of 't' in 's' (1-based)
# =========================================================

s = "ACCGAGCACCGAGCAATCCGAGCATTTATCCGAGCACACCGAGCACCGAGCACCGAGCAATGGCCGAGCACCCCGAGCACGGCCGAGCATCCGAGCAGCCGAGCAACCGAGCACCGAGCACCGAGCATACCTCCGAGCACCGAGCACCGAGCATTTGGGTGGTGCCGAGCAATCCGAGCACCGAGCACCGAGCACCGAGCACCCGAGCACCGAGCACCCGAGCAGCTCCCTTTCCGAGCATGGCCGAGCAGTATTCCCGAGCATGCGTACCGAGCATTCCGGGCCGAGCAAAGCCCCTATTCCGAGCAGTACCGAGCACCGAGCAATAGGGTCCGAGCATTAGAGTGACCCGAGCATGAATTCCGAGCATCCGAGCATGTGTCCCGAGCAACTGCCCCCGAGCAGGCCGAGCACCGAGCAGGACCGAGCAGGTCCGAGCACCGAGCACCGAGCAGGCCCGAGCAGTACTCCGAGCATACCGAGCATTCAACCGAGCACCGAGCACCGAGCAGGATCATAAGGTCCGAGCATTGCGGCCGAGCACTTGCCGAGCACCGAGCAATGGTATCCGAGCACCGAGCACACCGAGCACCGAGCACCGAGCAACTACCGAGCACCGAGCAGCCGAGCACCCGAGCACCGAGCATACCGAGCATCCCGAGCAAGAAGCCGAGCACCGAGCACGACCGAGCACCGAGCACCGAGCATTCTCCGAGCACCGAGCAGAGTATACCGAGCACCGAGCACTGTCCGAGCACACCCGACTCCGAGCACGTGGGCCGAGCATCCGAGCACCGAGCACCGAGCATCCGAGCAGTCAGCCGAGCA"
t = "CCGAGCACC"

# ---------------------------------------------------------
# DO NOT EDIT BELOW THIS LINE
# ---------------------------------------------------------
# Find all starting positions of t in s (1-based indexing)
positions = []

for i in range(len(s) - len(t) + 1):
    if s[i:i + len(t)] == t:
        positions.append(i + 1)

# Print results in Rosalind format
print("Your Rosalind answer is:")
print(" ".join(map(str, positions)))
